### ISSUE TITLE
mat1 and mat2 shapes cannot be multiplied (1x38400 and 800x64)

### ISSUE THREAD

**Issue by csingh27** [csingh27/trident_primitives#6]
Traceback (most recent call last):
  File "/home/dfki.uni-bremen.de/csingh/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dfki.uni-bremen.de/csingh/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dfki.uni-bremen.de/csingh/DFKI/PhysWM/trident_primitives/src/trident_train.py", line 104, in <module>
    evaluation_loss, evaluation_accuracy = inner_adapt_trident(
  File "/home/dfki.uni-bremen.de/csingh/DFKI/PhysWM/trident_primitives/src/zoo/trident_utils.py", line 138, in inner_adapt_trident
    reconst_image, logits, mu_l, log_var_l, mu_s, log_var_s = learner(
  File "/home/dfki.uni-bremen.de/csingh/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dfki.uni-bremen.de/csingh/anaconda3/lib/python3.9/site-packages/learn2learn/algorithms/maml.py", line 107, in forward
    return self.module(*args, **kwargs)
  File "/home/dfki.uni-bremen.de/csingh/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dfki.uni-bremen.de/csingh/DFKI/PhysWM/trident_primitives/src/zoo/archs.py", line 810, in forward
    mu_s, log_var_s = self.gaussian_parametrizer(xs)
  File "/home/dfki.uni-bremen.de/csingh/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dfki.uni-bremen.de/csingh/DFKI/PhysWM/trident_primitives/src/zoo/archs.py", line 404, in forward
    mu = self.h1(x)
  File "/home/dfki.uni-bremen.de/csingh/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dfki.uni-bremen.de/csingh/anaconda3/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x38400 and 800x64)

**Comment by csingh27** [comment]
resizing fixed the problem
